/**
 * Menu lengkap Rolun Coffee & Pastry, disalin dari buku menu resmi.
 * Harga dalam Rupiah (IDR). `category` dipakai untuk tab di halaman menu;
 * `group` mengelompokkan item di dalam satu tab. Sebagian kecil item memakai
 * foto asli — selebihnya tampil dengan monogram khas brand.
 */

export type MenuCategory =
  | "Coffee"
  | "Non Coffee"
  | "Tea"
  | "Pastry"
  | "Main Course"
  | "Snacks";

export type MenuTag = "signature" | "chef" | "spicy" | "new";

export interface MenuItem {
  id: string;
  name: string;
  category: MenuCategory;
  group: string;
  description: string;
  price: number;
  /** mis. "per pcs", "per teko" */
  unit?: string;
  tags?: MenuTag[];
  image?: string;
  /** ditampilkan di bagian signature halaman beranda */
  featured?: boolean;
}

/** Label tab kategori dalam Bahasa Indonesia (kunci tetap Inggris untuk type-safety). */
export const CATEGORY_LABEL: Record<MenuCategory, string> = {
  Coffee: "Kopi",
  "Non Coffee": "Non-Kopi",
  Tea: "Teh",
  Pastry: "Pastry",
  "Main Course": "Makanan Utama",
  Snacks: "Cemilan",
};

export const MENU_CATEGORIES: {
  id: MenuCategory;
  label: string;
  blurb: string;
}[] = [
  { id: "Coffee", label: "Kopi", blurb: "Espresso house, single origin & cold brew" },
  { id: "Non Coffee", label: "Non-Kopi", blurb: "Cokelat, milkshake, mojito & smoothies" },
  { id: "Tea", label: "Teh", blurb: "Teh premium & teh buah dingin" },
  { id: "Pastry", label: "Pastry", blurb: "Croissant, kue & dessert artisan" },
  { id: "Main Course", label: "Makanan Utama", blurb: "Hidangan nusantara, steak, pasta & pizza" },
  { id: "Snacks", label: "Cemilan", blurb: "Appetizer, salad & menu untuk berbagi" },
];

export const MENU: MenuItem[] = [
  // ───────────────────────── KOPI ─────────────────────────
  {
    id: "hot-coffee-rolun",
    name: "Hot Coffee Rolun",
    category: "Coffee",
    group: "Kopi Panas",
    description: "Kopi susu signature ala rumah — jiwa Rolun dalam satu cangkir.",
    price: 32000,
    tags: ["signature"],
    image: "/images/latte-art.webp",
    featured: true,
  },
  {
    id: "ice-coffee-rolun",
    name: "Ice Coffee Rolun",
    category: "Coffee",
    group: "Kopi Dingin",
    description:
      "Es kopi signature dengan gula aren buatan sendiri. Tersedia juga dalam botol untuk dibawa pulang.",
    price: 32500,
    tags: ["signature"],
    featured: true,
  },
  {
    id: "rempah-latte",
    name: "Rempah Latte",
    category: "Coffee",
    group: "Kopi Dingin",
    description:
      "Racikan rempah pilihan dan gula aren — kopi signature yang disajikan dengan penuh kehangatan.",
    price: 34000,
    tags: ["signature"],
    featured: true,
  },
  {
    id: "hot-dolce-latte",
    name: "Hot Dolce Latte",
    category: "Coffee",
    group: "Kopi Panas",
    description: "Sirup vanila, susu kental manis, ekstrak kopi & susu segar.",
    price: 33000,
  },
  {
    id: "baby-chino",
    name: "Baby Chino",
    category: "Coffee",
    group: "Kopi Panas",
    description: "Susu segar, sirup vanila & gula aren dengan marshmallow panggang di atasnya.",
    price: 28500,
  },
  {
    id: "creme-brulle-coffee",
    name: "Crème Brûlée Latte",
    category: "Coffee",
    group: "Kopi Panas",
    description: "Double ristretto, sirup hazelnut, susu, dan gula aren yang dibakar.",
    price: 32000,
    tags: ["chef"],
  },
  {
    id: "caramel-macchiato-hot",
    name: "Caramel Macchiato",
    category: "Coffee",
    group: "Kopi Panas",
    description: "Double ristretto, sirup karamel, susu, dan saus karamel.",
    price: 32000,
  },
  {
    id: "cappucino",
    name: "Cappuccino",
    category: "Coffee",
    group: "Kopi Panas",
    description: "Double ristretto dengan susu berbusa lembut.",
    price: 28000,
  },
  {
    id: "latte",
    name: "Caffè Latte",
    category: "Coffee",
    group: "Kopi Panas",
    description: "Double ristretto dengan susu steam yang halus.",
    price: 28000,
  },
  {
    id: "mochaccino",
    name: "Mochaccino",
    category: "Coffee",
    group: "Kopi Panas",
    description: "Bubuk cokelat, double ristretto & susu berbusa.",
    price: 28000,
  },
  {
    id: "espresso",
    name: "Espresso",
    category: "Coffee",
    group: "Kopi Panas",
    description: "Double shot dengan sparkling sebagai penyegar.",
    price: 22000,
  },
  {
    id: "americano",
    name: "Americano",
    category: "Coffee",
    group: "Kopi Panas",
    description: "Double shot yang dipanjangkan dengan air panas.",
    price: 26000,
  },
  {
    id: "v60",
    name: "V60 Pour Over",
    category: "Coffee",
    group: "Manual Brew",
    description: "Seduh manual dari biji house roast signature Rolun.",
    price: 28000,
  },
  {
    id: "japanese-coffee",
    name: "Japanese Iced Coffee",
    category: "Coffee",
    group: "Manual Brew",
    description: "Kopi giling signature Rolun yang diseduh langsung di atas es.",
    price: 32500,
  },
  {
    id: "kopi-tubruk",
    name: "Kopi Tubruk",
    category: "Coffee",
    group: "Manual Brew",
    description: "Kopi tubruk tradisional, bold dan tanpa saringan.",
    price: 25000,
  },
  {
    id: "ice-hazelnut-latte",
    name: "Ice Hazelnut Latte",
    category: "Coffee",
    group: "Kopi Dingin",
    description: "Susu segar, sirup hazelnut & double ristretto dengan es.",
    price: 32500,
  },
  {
    id: "ice-dolce-latte",
    name: "Ice Dolce Latte",
    category: "Coffee",
    group: "Kopi Dingin",
    description: "Susu segar, sirup vanila, susu kental manis & double ristretto.",
    price: 33000,
  },
  {
    id: "ice-caramel-macchiato",
    name: "Ice Caramel Macchiato",
    category: "Coffee",
    group: "Kopi Dingin",
    description: "Susu segar, sirup salted caramel & double ristretto di atas es.",
    price: 35000,
  },
  {
    id: "ice-latte",
    name: "Ice Latte",
    category: "Coffee",
    group: "Kopi Dingin",
    description: "Double ristretto dengan susu segar dingin.",
    price: 28500,
  },
  {
    id: "ice-americano",
    name: "Ice Americano",
    category: "Coffee",
    group: "Kopi Dingin",
    description: "Double shot dengan es dan air.",
    price: 28000,
  },
  {
    id: "classic-affogato",
    name: "Classic Affogato",
    category: "Coffee",
    group: "Kopi Dingin",
    description: "Satu shot espresso yang dituang di atas es krim vanila.",
    price: 28000,
  },
  {
    id: "passionate-coffee",
    name: "Passionate Coffee",
    category: "Coffee",
    group: "Coffee Mocktail",
    description: "Cold brew dengan sirup markisa, vanila & lemon, disempurnakan dengan soda.",
    price: 32000,
  },
  {
    id: "apple-fuzz",
    name: "Apple Fuzz",
    category: "Coffee",
    group: "Coffee Mocktail",
    description: "Cold brew dengan sirup stroberi & lemon serta jus apel.",
    price: 32000,
  },
  {
    id: "gummy-gum",
    name: "Gummy Gum",
    category: "Coffee",
    group: "Coffee Mocktail",
    description: "Mocktail cold brew dengan blueberry dan lemon.",
    price: 32000,
  },
  {
    id: "peanut-latte",
    name: "Peanut Latte",
    category: "Coffee",
    group: "Kopi Dingin",
    description: "Selai kacang yang berpadu dengan kopi susu.",
    price: 32000,
  },

  // ───────────────────────── NON-KOPI ─────────────────────────
  {
    id: "hot-chocolate",
    name: "Hot Chocolate",
    category: "Non Coffee",
    group: "Cokelat & Latte",
    description: "Bubuk cokelat pekat dengan susu berbusa.",
    price: 32500,
  },
  {
    id: "matcha-latte",
    name: "Matcha Latte",
    category: "Non Coffee",
    group: "Cokelat & Latte",
    description: "Bubuk matcha pilihan dengan susu berbusa.",
    price: 32500,
  },
  {
    id: "taro-latte",
    name: "Taro Latte",
    category: "Non Coffee",
    group: "Cokelat & Latte",
    description: "Taro yang creamy dengan susu berbusa.",
    price: 32000,
  },
  {
    id: "ice-chocolate",
    name: "Ice Chocolate",
    category: "Non Coffee",
    group: "Cokelat & Latte",
    description: "Sirup cokelat, simple syrup & susu segar di atas es.",
    price: 32000,
  },
  {
    id: "ice-matcha-latte",
    name: "Ice Matcha Latte",
    category: "Non Coffee",
    group: "Cokelat & Latte",
    description: "Bubuk matcha, susu segar & simple syrup di atas es.",
    price: 35000,
  },
  {
    id: "rolun-mojito",
    name: "Rolun Mojito",
    category: "Non Coffee",
    group: "Mojito",
    description: "Blue ocean, grenadine, lemon & mint dengan special mojito dan soda.",
    price: 35000,
    tags: ["signature"],
  },
  {
    id: "mix-berry-mojito",
    name: "Mix Berry Mojito",
    category: "Non Coffee",
    group: "Mojito",
    description: "Mixed berry, lemon, mint & soda dengan stroberi segar.",
    price: 33500,
  },
  {
    id: "kiwi-mojito",
    name: "Kiwi Mojito",
    category: "Non Coffee",
    group: "Mojito",
    description: "Kiwi, lemon, mint & special mojito dengan soda.",
    price: 35000,
  },
  {
    id: "lychee-mojito",
    name: "Lychee Mojito",
    category: "Non Coffee",
    group: "Mojito",
    description: "Leci, lemon & mint dengan soda dan buah leci.",
    price: 33500,
  },
  {
    id: "passion-fruit-mojito",
    name: "Passion Fruit Mojito",
    category: "Non Coffee",
    group: "Mojito",
    description: "Markisa, lemon & mint dengan soda.",
    price: 33500,
  },
  {
    id: "blue-ocean",
    name: "Blue Ocean",
    category: "Non Coffee",
    group: "Mocktail",
    description: "Sirup blue ocean, sirsak & lemon dengan soda.",
    price: 30000,
  },
  {
    id: "black-lemonade",
    name: "Black Lemonade",
    category: "Non Coffee",
    group: "Mocktail",
    description: "Sirup lemon & simple syrup dengan espresso dan soda.",
    price: 32000,
  },
  {
    id: "sunday-cloud",
    name: "Sunday Cloud",
    category: "Non Coffee",
    group: "Mocktail",
    description: "Sirup vanila & blue ocean, yakult, dan whipped cream.",
    price: 32000,
  },
  {
    id: "wedang-jahe",
    name: "Wedang Jahe",
    category: "Non Coffee",
    group: "Mocktail",
    description: "Jahe dan serai yang diseduh dengan rempah rahasia khas rumah.",
    price: 32000,
  },
  {
    id: "salted-caramel-shake",
    name: "Salted Caramel Shake",
    category: "Non Coffee",
    group: "Milkshake",
    description: "Karamel, saus salted caramel & susu, dilengkapi whipped cream.",
    price: 39500,
  },
  {
    id: "choco-milkshake",
    name: "Choco Milkshake",
    category: "Non Coffee",
    group: "Milkshake",
    description: "Cokelat, es krim vanila & susu dengan whipped cream di atasnya.",
    price: 36000,
  },
  {
    id: "choco-berry-milkshake",
    name: "Choco Berry Milkshake",
    category: "Non Coffee",
    group: "Milkshake",
    description: "Cokelat, es krim, mint, puree stroberi & whipped cream.",
    price: 38500,
  },
  {
    id: "matcha-milkshake",
    name: "Matcha Milkshake",
    category: "Non Coffee",
    group: "Milkshake",
    description: "Matcha, es krim vanila & susu dengan whipped cream di atasnya.",
    price: 36000,
  },
  {
    id: "taro-milkshake",
    name: "Taro Milkshake",
    category: "Non Coffee",
    group: "Milkshake",
    description: "Taro, es krim & susu dengan whipped cream di atasnya.",
    price: 36000,
  },
  {
    id: "regal-blend",
    name: "Regal Blend",
    category: "Non Coffee",
    group: "Milkshake",
    description: "Biskuit regal, karamel, es krim vanila & whipped cream.",
    price: 38500,
  },
  {
    id: "cookies-and-cream",
    name: "Cookies & Cream",
    category: "Non Coffee",
    group: "Milkshake",
    description: "Oreo, simple syrup, es krim & susu dengan whipped cream.",
    price: 36000,
  },
  {
    id: "berry-smoothies",
    name: "Berry Smoothies",
    category: "Non Coffee",
    group: "Smoothies",
    description: "Mixed berry, susu segar, simple syrup & yoghurt.",
    price: 35000,
  },
  {
    id: "kiwi-smoothies",
    name: "Kiwi Smoothies",
    category: "Non Coffee",
    group: "Smoothies",
    description: "Daging buah kiwi, susu segar, simple syrup & yoghurt.",
    price: 35000,
  },
  {
    id: "blueberry-smoothies",
    name: "Blueberry Smoothies",
    category: "Non Coffee",
    group: "Smoothies",
    description: "Selai blueberry, simple syrup, yoghurt & susu segar.",
    price: 36000,
  },
  {
    id: "creamy-butter",
    name: "Creamy Butter",
    category: "Non Coffee",
    group: "Smoothies",
    description: "Butterscotch, salted caramel, susu & whipped cream.",
    price: 33000,
  },
  {
    id: "salted-caramel-float",
    name: "Salted Caramel Float",
    category: "Non Coffee",
    group: "Float",
    description: "Es krim vanila dengan topping salted caramel dan regal.",
    price: 28500,
  },
  {
    id: "matchagatto",
    name: "Matchagatto",
    category: "Non Coffee",
    group: "Float",
    description: "Es krim vanila dengan topping matcha.",
    price: 28000,
  },
  {
    id: "dark-berry-float",
    name: "Dark Berry Float",
    category: "Non Coffee",
    group: "Float",
    description: "Es krim vanila dengan topping mixed berry dan cokelat.",
    price: 26000,
  },
  {
    id: "fresh-bcp-juice",
    name: "Fresh BCP Juice",
    category: "Non Coffee",
    group: "Jus Segar",
    description: "Bit, wortel, dan nanas yang diperas segar.",
    price: 38000,
  },
  {
    id: "natural-green-boost",
    name: "Natural Green Boost",
    category: "Non Coffee",
    group: "Jus Segar",
    description: "Kale, romaine, jeruk sunkist, dan apel.",
    price: 38500,
    tags: ["chef"],
  },
  {
    id: "sweet-booster-juice",
    name: "Sweet Booster",
    category: "Non Coffee",
    group: "Jus Segar",
    description: "Apel, wortel, dan jahe.",
    price: 38000,
  },
  {
    id: "avocado-juice",
    name: "Avocado Juice",
    category: "Non Coffee",
    group: "Jus Segar",
    description: "Alpukat segar yang diblender ala rumah.",
    price: 33500,
  },
  {
    id: "orange-juice",
    name: "Orange Juice",
    category: "Non Coffee",
    group: "Jus Segar",
    description: "Jeruk peras segar.",
    price: 33000,
  },
  {
    id: "lemongrass-juice",
    name: "Lemongrass Juice",
    category: "Non Coffee",
    group: "Jus Segar",
    description: "Serai dengan perasan lemon.",
    price: 33000,
  },

  // ───────────────────────── TEH ─────────────────────────
  {
    id: "forest-berries-tea",
    name: "Forest Berries Tea",
    category: "Tea",
    group: "Teh Panas",
    description: "Teh forest berries premium yang diseduh dalam teko.",
    price: 26500,
    tags: ["signature"],
  },
  {
    id: "english-breakfast-tea",
    name: "English Breakfast Tea",
    category: "Tea",
    group: "Teh Panas",
    description: "Teh English breakfast premium disajikan dalam teko.",
    price: 25000,
  },
  {
    id: "earl-grey-tea",
    name: "Earl Grey Tea",
    category: "Tea",
    group: "Teh Panas",
    description: "Teh earl grey bergamot premium disajikan dalam teko.",
    price: 25000,
  },
  {
    id: "chamomile-tea",
    name: "Chamomile Tea",
    category: "Tea",
    group: "Teh Panas",
    description: "Teh chamomile premium yang menenangkan, disajikan dalam teko.",
    price: 25000,
  },
  {
    id: "hot-lemon-tea",
    name: "Hot Lemon Tea",
    category: "Tea",
    group: "Teh Panas",
    description: "Teh dengan irisan lemon segar disajikan dalam mug.",
    price: 25000,
  },
  {
    id: "golden-ice-tea",
    name: "Golden Ice Tea",
    category: "Tea",
    group: "Teh Dingin",
    description: "Teh dengan sirup osmanthus, apel, melati & lemon.",
    price: 28000,
  },
  {
    id: "ice-lychee-tea",
    name: "Ice Lychee Tea",
    category: "Tea",
    group: "Teh Dingin",
    description: "Teh dengan sirup leci dan buah leci segar.",
    price: 28000,
  },
  {
    id: "ice-lemon-tea",
    name: "Ice Lemon Tea",
    category: "Tea",
    group: "Teh Dingin",
    description: "Teh dengan lemon dan simple syrup di atas es.",
    price: 28000,
  },
  {
    id: "sakura-ice-tea",
    name: "Sakura Ice Tea",
    category: "Tea",
    group: "Teh Dingin",
    description: "Teh dengan sirup sakura & melati serta jus apel.",
    price: 28000,
  },
  {
    id: "passion-fruit-tea",
    name: "Passion Fruit Tea",
    category: "Tea",
    group: "Teh Dingin",
    description: "Teh dengan markisa, lemon, dan simple syrup.",
    price: 28000,
  },

  // ───────────────────────── PASTRY ─────────────────────────
  {
    id: "rolun-redvelvet",
    name: "Rolun Redvelvet",
    category: "Pastry",
    group: "Kue & Dessert",
    description: "Butter cake berlapis cream cheese yang lembut.",
    price: 45000,
    tags: ["signature"],
    image: "/images/pastry-case.webp",
    featured: true,
  },
  {
    id: "dubai-choco-cake",
    name: "Dubai Choco Cake",
    category: "Pastry",
    group: "Kue & Dessert",
    description:
      "Sponge cokelat premium dengan ganache cokelat dan kunafa pistachio buatan sendiri.",
    price: 50000,
    tags: ["signature"],
    featured: true,
  },
  {
    id: "almond-croissant",
    name: "Almond Croissant",
    category: "Pastry",
    group: "Croissant",
    description: "Croissant mentega berisi dan bertabur almond panggang.",
    price: 30000,
    image: "/images/table-coffee-croissant.webp",
    featured: true,
  },
  {
    id: "choco-hazelnut-cheesecake",
    name: "Choco Hazelnut Cheese Cake",
    category: "Pastry",
    group: "Kue & Dessert",
    description: "New York cheesecake dengan choco hazelnut buatan sendiri.",
    price: 42000,
    featured: true,
  },
  {
    id: "blueberry-cheesecake",
    name: "Blueberry Cheese Cake",
    category: "Pastry",
    group: "Kue & Dessert",
    description: "New York cheesecake dengan topping selai blueberry.",
    price: 40000,
  },
  {
    id: "strawberry-cheesecake",
    name: "Strawberry Cheese Cake",
    category: "Pastry",
    group: "Kue & Dessert",
    description: "New York cheesecake dengan topping selai stroberi.",
    price: 40000,
    tags: ["chef"],
  },
  {
    id: "choco-tiramisu-cake",
    name: "Choco Tiramisu Cake",
    category: "Pastry",
    group: "Kue & Dessert",
    description: "Sponge coffee-choco dengan krim mascarpone dan ganache cokelat.",
    price: 45000,
  },
  {
    id: "rainbow-cake",
    name: "Rainbow Cake",
    category: "Pastry",
    group: "Kue & Dessert",
    description: "Butter cake berlapis dengan cita rasa signature.",
    price: 50000,
    tags: ["chef"],
  },
  {
    id: "pistachio-cheesecake",
    name: "Pistachio Cheese Cake",
    category: "Pastry",
    group: "Kue & Dessert",
    description: "New York cheesecake dengan pasta pistachio buatan sendiri.",
    price: 42000,
  },
  {
    id: "klepon-cake",
    name: "Klepon Cake",
    category: "Pastry",
    group: "Kue & Dessert",
    description: "Sponge pandan, gula aren, krim kelapa & kelapa parut.",
    price: 35000,
  },
  {
    id: "molten-lava-cake",
    name: "Molten Lava Cake",
    category: "Pastry",
    group: "Kue & Dessert",
    description: "Choco lava cake dengan es krim vanila, granola & stroberi.",
    price: 40000,
    tags: ["chef"],
  },
  {
    id: "panna-cotta",
    name: "Panna Cotta",
    category: "Pastry",
    group: "Kue & Dessert",
    description: "Panna cotta creamy dengan es krim, saus jeruk & granola.",
    price: 37000,
    tags: ["chef"],
  },
  {
    id: "caramel-custard",
    name: "Caramel Custard",
    category: "Pastry",
    group: "Kue & Dessert",
    description: "Custard dengan es krim vanila, karamel, granola & buah.",
    price: 37000,
  },
  {
    id: "apple-crumble",
    name: "Apple Crumble",
    category: "Pastry",
    group: "Kue & Dessert",
    description: "Butter cake dengan cream cheese dan apel kayu manis.",
    price: 22000,
  },
  {
    id: "korean-bento-cake",
    name: "Korean Bento Cake",
    category: "Pastry",
    group: "Kue & Dessert",
    description: "Kue lunchbox mungil — bisa dikustom sesuai permintaan.",
    price: 70000,
    tags: ["new"],
  },
  {
    id: "tiramisu-classic",
    name: "Tiramisu Classic",
    category: "Pastry",
    group: "Kue & Dessert",
    description: "Tiramisu mascarpone klasik dengan taburan kakao.",
    price: 37000,
    tags: ["new"],
  },
  {
    id: "muffin-chocolate",
    name: "Chocolate Muffin",
    category: "Pastry",
    group: "Kue & Dessert",
    description: "Muffin cokelat lembut yang dipanggang setiap hari.",
    price: 21500,
    tags: ["new"],
  },
  {
    id: "macaron",
    name: "French Macaron",
    category: "Pastry",
    group: "Patisserie",
    description:
      "Rasa berganti setiap hari — matcha, pistachio, salted caramel, stroberi & lainnya.",
    price: 19000,
    unit: "per pcs",
    image: "/images/macarons.webp",
  },
  {
    id: "butter-croissant",
    name: "Butter Croissant",
    category: "Pastry",
    group: "Croissant",
    description: "Croissant butter klasik, berlapis dan renyah.",
    price: 18500,
  },
  {
    id: "pain-au-chocolat",
    name: "Pain au Chocolat",
    category: "Pastry",
    group: "Croissant",
    description: "Pastry berlapis dengan isian batang cokelat hitam.",
    price: 22000,
  },
  {
    id: "smoked-beef-cheese-croissant",
    name: "Smoked Beef & Cheese Croissant",
    category: "Pastry",
    group: "Croissant",
    description: "Croissant gurih isi smoked beef dan keju.",
    price: 27000,
    tags: ["chef"],
  },
  {
    id: "cinnamon-roll-croissant",
    name: "Cinnamon Roll Croissant",
    category: "Pastry",
    group: "Croissant",
    description: "Adonan croissant yang digulung dengan gula kayu manis.",
    price: 25000,
  },
  {
    id: "ovomaltine-croissant",
    name: "Ovomaltine Croissant",
    category: "Pastry",
    group: "Croissant",
    description: "Croissant isi krim ovomaltine yang renyah.",
    price: 30000,
  },
  {
    id: "choco-almond-croissant",
    name: "Choco Almond Croissant",
    category: "Pastry",
    group: "Croissant",
    description: "Croissant berlapis cokelat dan almond panggang.",
    price: 26500,
  },
  {
    id: "crookie",
    name: "Crookie",
    category: "Pastry",
    group: "Croissant",
    description: "Croissant berisi adonan cookie choco chip.",
    price: 25000,
    tags: ["chef"],
  },
  {
    id: "cromboloni-double-choco",
    name: "Cromboloni Double Choco",
    category: "Pastry",
    group: "Croissant",
    description: "Croissant bulat isi dan glaze double cokelat.",
    price: 28000,
  },

  // ───────────────────────── MAKANAN UTAMA ─────────────────────────
  {
    id: "nasi-goreng-rolun",
    name: "Nasi Goreng Rolun",
    category: "Main Course",
    group: "Nasi & Mie",
    description: "Nasi goreng signature dengan ayam krispi dan telur mata sapi.",
    price: 58500,
    tags: ["signature", "chef", "spicy"],
  },
  {
    id: "nasi-goreng-kampung",
    name: "Nasi Goreng Kampung",
    category: "Main Course",
    group: "Nasi & Mie",
    description: "Nasi goreng tradisional dengan ayam dan telur mata sapi.",
    price: 58500,
  },
  {
    id: "nasi-goreng-iga-rempah",
    name: "Nasi Goreng Iga Rempah",
    category: "Main Course",
    group: "Nasi & Mie",
    description: "Nasi goreng dengan iga, rempah nusantara, dan telur mata sapi.",
    price: 59000,
  },
  {
    id: "mie-goreng-rolun",
    name: "Mie Goreng Rolun",
    category: "Main Course",
    group: "Nasi & Mie",
    description: "Mie goreng signature dengan topping chicken katsu.",
    price: 55000,
    tags: ["signature", "chef"],
  },
  {
    id: "nasi-campur-bali",
    name: "Nasi Campur Bali",
    category: "Main Course",
    group: "Nasi & Mie",
    description: "Nasi dengan sate, sayur, kulit ayam, sambal matah, telur & plecing.",
    price: 59500,
    tags: ["chef"],
  },
  {
    id: "nasi-bebek",
    name: "Nasi Bebek",
    category: "Main Course",
    group: "Nasi & Mie",
    description: "Nasi mentega dengan bebek goreng, kerupuk melinjo, sambal & acar.",
    price: 89500,
    tags: ["chef"],
  },
  {
    id: "chicken-katsu-curry",
    name: "Chicken Katsu Curry",
    category: "Main Course",
    group: "Nasi & Mie",
    description: "Nasi putih dengan chicken katsu dan brokoli siram saus kari.",
    price: 49500,
  },
  {
    id: "chicken-mango",
    name: "Chicken Mango",
    category: "Main Course",
    group: "Nasi & Mie",
    description: "Nasi putih dengan ayam strip dan saus mangga signature.",
    price: 53500,
    tags: ["chef"],
  },
  {
    id: "nasi-bakar-teri",
    name: "Nasi Bakar Teri",
    category: "Main Course",
    group: "Nasi & Mie",
    description: "Nasi bakar teri medan dengan ayam bakar/goreng & sambal.",
    price: 59500,
  },
  {
    id: "rolun-rice-bowl",
    name: "Rolun Rice Bowl",
    category: "Main Course",
    group: "Rice Bowl",
    description: "Nasi nori dengan telur mata sapi, chicken pop, dan kerupuk.",
    price: 53500,
    tags: ["signature", "chef"],
  },
  {
    id: "rice-bowl-beef-teriyaki",
    name: "Rice Bowl Beef Teriyaki",
    category: "Main Course",
    group: "Rice Bowl",
    description: "Beef short plate saus teriyaki, coleslaw, keripik & telur mata sapi.",
    price: 48500,
  },
  {
    id: "rice-bowl-spicy-karage",
    name: "Rice Bowl Spicy Karage",
    category: "Main Course",
    group: "Rice Bowl",
    description: "Chicken pop saus karage pedas, coleslaw & telur mata sapi.",
    price: 47500,
    tags: ["spicy"],
  },
  {
    id: "rice-bowl-salmon-katsu",
    name: "Rice Bowl Salmon Katsu",
    category: "Main Course",
    group: "Rice Bowl",
    description: "Salmon katsu, telur mata sapi, coleslaw, teriyaki & wijen.",
    price: 55500,
    tags: ["chef"],
  },
  {
    id: "tenderloin-steak",
    name: "Tenderloin Steak",
    category: "Main Course",
    group: "Steak",
    description: "Tenderloin panggang dengan salad segar, saus jamur & kentang goreng.",
    price: 125000,
    tags: ["chef"],
  },
  {
    id: "sirloin-steak",
    name: "Sirloin Steak",
    category: "Main Course",
    group: "Steak",
    description: "Sirloin premium dengan saus jamur, salad segar & kentang goreng.",
    price: 115500,
  },
  {
    id: "tokyo-steak",
    name: "Tokyo Steak",
    category: "Main Course",
    group: "Steak",
    description: "Nasi mentega dengan sirloin meltique wagyu, teriyaki & telur.",
    price: 135000,
    tags: ["chef"],
  },
  {
    id: "tbone-steak",
    name: "T-Bone Steak",
    category: "Main Course",
    group: "Steak",
    description: "T-bone dengan salad, baby potato dan saus barbeque, tingkat medium well.",
    price: 138000,
  },
  {
    id: "salmon-steak",
    name: "Salmon Steak",
    category: "Main Course",
    group: "Steak",
    description: "Salmon pan-seared, saus teriyaki, potato wedges & salad.",
    price: 135500,
  },
  {
    id: "chicken-steak",
    name: "Chicken Steak",
    category: "Main Course",
    group: "Steak",
    description: "Dada ayam panggang, salad segar, kentang goreng dan saus gravy.",
    price: 68500,
    image: "/images/signature-platter.webp",
  },
  {
    id: "spaghetti-bolognese",
    name: "Spaghetti Bolognese",
    category: "Main Course",
    group: "Pasta",
    description: "Bolognese dengan garlic bread dan keju cheddar di atasnya.",
    price: 52500,
  },
  {
    id: "salmon-carbonara",
    name: "Salmon Carbonara",
    category: "Main Course",
    group: "Pasta",
    description: "Carbonara creamy dengan salmon dan garlic bread.",
    price: 59000,
  },
  {
    id: "carbonara-smoked-beef",
    name: "Carbonara Smoked Beef",
    category: "Main Course",
    group: "Pasta",
    description: "Carbonara creamy dengan smoked beef dan garlic bread.",
    price: 57500,
    tags: ["chef"],
  },
  {
    id: "spaghetti-spicy-mushroom",
    name: "Spaghetti Spicy Mushroom",
    category: "Main Course",
    group: "Pasta",
    description: "Ayam pedas, cabai, jamur champignon & parmesan.",
    price: 52500,
    tags: ["chef", "spicy"],
  },
  {
    id: "aglio-dori",
    name: "Spaghetti Aglio Dori",
    category: "Main Course",
    group: "Pasta",
    description: "Aglio olio pedas dengan dori, bawang putih dan cabai merah.",
    price: 52500,
    tags: ["spicy"],
  },
  {
    id: "alfredo-fettucine",
    name: "Alfredo Fettucine",
    category: "Main Course",
    group: "Pasta",
    description: "Alfredo creamy dengan jamur, ayam, dan garlic bread.",
    price: 52500,
  },
  {
    id: "rolun-beef-burger",
    name: "Rolun Beef Burger",
    category: "Main Course",
    group: "Burger & Sandwich",
    description: "Beef patty, tomat segar, beef mayo dan potato chips.",
    price: 55000,
  },
  {
    id: "double-cheese-burger",
    name: "Double Cheese Burger",
    category: "Main Course",
    group: "Burger & Sandwich",
    description: "Beef patty, tomat, saus keju dan potato chips.",
    price: 60000,
  },
  {
    id: "zesty-slider",
    name: "Zesty Slider",
    category: "Main Course",
    group: "Burger & Sandwich",
    description: "Dua mini burger — beef caramel onion & ayam pan-seared.",
    price: 50000,
    tags: ["chef"],
  },
  {
    id: "chicken-cordon-bleu",
    name: "Chicken Cordon Bleu",
    category: "Main Course",
    group: "Western",
    description: "Ayam goreng isi mozzarella & smoked beef, kentang goreng, gravy.",
    price: 73500,
    tags: ["chef"],
  },
  {
    id: "fish-and-fries",
    name: "Fish & Fries",
    category: "Main Course",
    group: "Western",
    description: "Dori goreng, kentang goreng, salad, saus tartar & lemon.",
    price: 69500,
    tags: ["chef"],
  },
  {
    id: "lasagna",
    name: "Lasagna",
    category: "Main Course",
    group: "Western",
    description: "Lasagna bolognese & béchamel berlapis mozzarella, dengan salad.",
    price: 53500,
  },
  {
    id: "mac-and-cheese",
    name: "Mac & Cheese",
    category: "Main Course",
    group: "Western",
    description: "Makaroni dan keju dengan garlic bread dan saus khas rumah.",
    price: 52500,
  },
  {
    id: "sushi-salmon-mentai",
    name: "Sushi Salmon Mentai",
    category: "Main Course",
    group: "Japanese",
    description: "Sushi roll isi kani, cheddar & salmon, mentai di atasnya.",
    price: 76500,
  },
  {
    id: "california-roll",
    name: "California Roll",
    category: "Main Course",
    group: "Japanese",
    description: "Sushi roll isi kani, alpukat dan tobiko di atasnya.",
    price: 67500,
  },
  {
    id: "spicy-tuna-roll",
    name: "Spicy Tuna Roll",
    category: "Main Course",
    group: "Japanese",
    description: "Sushi roll isi spicy tuna dan saus wijen.",
    price: 72500,
    tags: ["spicy"],
  },
  {
    id: "iga-bakar-sambal-ijo",
    name: "Iga Bakar Sambal Ijo",
    category: "Main Course",
    group: "Sup & Tradisional",
    description: "Iga konro bakar, nasi putih, sup bening & sambal ijo.",
    price: 155000,
  },
  {
    id: "sop-buntut",
    name: "Sop Buntut",
    category: "Main Course",
    group: "Sup & Tradisional",
    description: "Sop buntut dengan nasi putih dan kerupuk melinjo.",
    price: 135000,
  },
  {
    id: "ayam-betutu",
    name: "Ayam Betutu",
    category: "Main Course",
    group: "Sup & Tradisional",
    description: "Ayam betutu Bali dengan sambal matah dan daun singkong kukus.",
    price: 68500,
    tags: ["chef"],
  },
  {
    id: "grilled-chicken-rosemary",
    name: "Grilled Chicken Rosemary",
    category: "Main Course",
    group: "Sup & Tradisional",
    description: "Setengah ayam BBQ, jagung bakar, jamur dan potato wedges.",
    price: 78500,
    tags: ["chef"],
  },
  {
    id: "rawon",
    name: "Rawon",
    category: "Main Course",
    group: "Sup & Tradisional",
    description: "Rawon daging dengan nasi, telur asin dan kerupuk.",
    price: 65000,
    tags: ["chef"],
  },
  {
    id: "rolun-pizza",
    name: "Rolun Pizza",
    category: "Main Course",
    group: "Pizza",
    description: "Tomat, sosis, daging, jamur, parmesan & mozzarella.",
    price: 58000,
    tags: ["signature"],
  },
  {
    id: "margherita-pizza",
    name: "Margherita Pizza",
    category: "Main Course",
    group: "Pizza",
    description: "Tomat, tomat ceri, basil segar dan mozzarella.",
    price: 55000,
  },
  {
    id: "pepperoni-pizza",
    name: "Pepperoni Pizza",
    category: "Main Course",
    group: "Pizza",
    description: "Saus tomat, pepperoni dan mozzarella.",
    price: 58000,
  },
  {
    id: "truffle-mushroom-pizza",
    name: "Truffle Mushroom Pizza",
    category: "Main Course",
    group: "Pizza",
    description: "Saus jamur putih, truffle oil dan mozzarella.",
    price: 60000,
    tags: ["chef"],
  },
  {
    id: "dubai-choco-pizza",
    name: "Italian Dubai Choco Pizza",
    category: "Main Course",
    group: "Pizza",
    description: "Pizza manis dengan kunafa pistachio dan cokelat hitam.",
    price: 52000,
    tags: ["signature"],
  },
  {
    id: "nutella-sweet-almond-pizza",
    name: "Nutella Sweet Almond Pizza",
    category: "Main Course",
    group: "Pizza",
    description: "Nutella, almond, stroberi, marshmallow & icing sugar.",
    price: 50000,
  },
  {
    id: "rolun-kids-meal",
    name: "Rolun Kids Meal",
    category: "Main Course",
    group: "Menu Anak",
    description:
      "Sosis, nugget atau chicken finger dengan nasi/kentang — termasuk hadiah spesial.",
    price: 58000,
  },

  // ───────────────────────── CEMILAN / APPETIZER ─────────────────────────
  {
    id: "rolun-platter",
    name: "Rolun Platter",
    category: "Snacks",
    group: "Sharing",
    description:
      "Kentang goreng, chicken wings & sosis BBQ dengan salad dan saus tartar.",
    price: 48500,
    tags: ["signature", "chef"],
    image: "/images/signature-platter.webp",
  },
  {
    id: "rolun-chicken-wings",
    name: "Rolun Chicken Wings",
    category: "Snacks",
    group: "Sharing",
    description: "Chicken wings signature dengan garlic butter dan parmesan.",
    price: 39500,
    tags: ["signature", "chef"],
  },
  {
    id: "spicy-chicken-wings",
    name: "Spicy Chicken Wings",
    category: "Snacks",
    group: "Sharing",
    description: "Wings krispi dengan saus manis pedas khas rumah.",
    price: 39500,
    tags: ["spicy"],
  },
  {
    id: "chicken-shawarma",
    name: "Chicken Shawarma",
    category: "Snacks",
    group: "Sharing",
    description: "Tortilla isi ayam, timun, tomat dan spicy mayo.",
    price: 38500,
  },
  {
    id: "quesadillas",
    name: "Quesadillas",
    category: "Snacks",
    group: "Sharing",
    description: "Bolognese pedas & mozzarella dengan salsa tomat dan tartar.",
    price: 52500,
  },
  {
    id: "nachos",
    name: "Nachos",
    category: "Snacks",
    group: "Sharing",
    description: "Tortilla jagung dengan daging cincang, salsa, jalapeño & mozzarella.",
    price: 38500,
    tags: ["chef", "spicy"],
  },
  {
    id: "calamari",
    name: "Calamari",
    category: "Snacks",
    group: "Sharing",
    description: "Cumi krispi dengan saus tartar buatan sendiri.",
    price: 39500,
  },
  {
    id: "chicken-finger",
    name: "Chicken Finger",
    category: "Snacks",
    group: "Sharing",
    description: "Chicken finger, kentang goreng dan salad dengan saus tartar.",
    price: 45500,
  },
  {
    id: "thai-beef-salad",
    name: "Thai Beef Salad",
    category: "Snacks",
    group: "Salad",
    description: "Irisan daging, bihun, wijen & dressing Thai.",
    price: 55000,
  },
  {
    id: "caesar-salad",
    name: "Caesar Salad",
    category: "Snacks",
    group: "Salad",
    description: "Romaine, dressing caesar, ayam panggang, telur & crouton.",
    price: 48500,
    tags: ["chef"],
  },
  {
    id: "fruit-salad",
    name: "Fruit Salad",
    category: "Snacks",
    group: "Salad",
    description: "Buah segar dengan dressing stroberi, sweet mayo & granola.",
    price: 42500,
  },
  {
    id: "cream-chicken-soup",
    name: "Cream Chicken Soup",
    category: "Snacks",
    group: "Sup",
    description: "Sup krim ayam disajikan dengan garlic bread.",
    price: 38500,
    tags: ["chef"],
  },
  {
    id: "potato-soup",
    name: "Potato Soup",
    category: "Snacks",
    group: "Sup",
    description: "Puree kentang dengan susu dan krim, dengan garlic bread.",
    price: 38500,
    tags: ["chef"],
  },
  {
    id: "mexican-corn",
    name: "Mexican Corn",
    category: "Snacks",
    group: "Cemilan",
    description: "Jagung manis panggang dengan cajun pedas dan tartar.",
    price: 32500,
    tags: ["chef"],
  },
  {
    id: "cajun-fries",
    name: "Cajun Fries",
    category: "Snacks",
    group: "Cemilan",
    description: "Kentang goreng bumbu cajun khas rumah.",
    price: 32500,
    tags: ["chef", "spicy"],
  },
  {
    id: "cheesy-fries",
    name: "Cheesy Fries",
    category: "Snacks",
    group: "Cemilan",
    description: "Kentang goreng dengan saus keju dan zaitun hitam.",
    price: 28000,
  },
  {
    id: "onion-ring",
    name: "Onion Ring",
    category: "Snacks",
    group: "Cemilan",
    description: "Onion ring krispi disajikan dengan spicy mayo.",
    price: 32500,
  },
  {
    id: "bruschetta",
    name: "Bruschetta",
    category: "Snacks",
    group: "Cemilan",
    description: "Garlic bread, jamur dan mozzarella dengan salad.",
    price: 28000,
  },
  {
    id: "churros",
    name: "Churros",
    category: "Snacks",
    group: "Cemilan Manis",
    description: "Churros kayu manis disajikan dengan saus cokelat.",
    price: 40000,
  },
  {
    id: "pisang-aroma",
    name: "Pisang Aroma",
    category: "Snacks",
    group: "Cemilan Manis",
    description: "Pisang dalam kulit lumpia renyah dengan es krim dan karamel.",
    price: 32500,
    tags: ["chef"],
  },
  {
    id: "pisang-goreng",
    name: "Pisang Goreng",
    category: "Snacks",
    group: "Cemilan Manis",
    description: "Pisang goreng dengan keju, cokelat dan gula aren.",
    price: 30000,
  },
  {
    id: "cireng-bumbu-rujak",
    name: "Cireng Bumbu Rujak",
    category: "Snacks",
    group: "Cemilan",
    description: "Cireng khas Sunda dengan sambal rujak.",
    price: 28000,
  },
  {
    id: "tahu-lada-garam",
    name: "Tahu Lada Garam",
    category: "Snacks",
    group: "Cemilan",
    description: "Tahu goreng dengan cabai merah dan bawang putih.",
    price: 32500,
  },
];

/** Item yang ditandai untuk bagian signature di halaman beranda. */
export const SIGNATURE_DRINKS = MENU.filter(
  (m) => m.featured && (m.category === "Coffee" || m.category === "Non Coffee"),
);
export const SIGNATURE_PASTRIES = MENU.filter(
  (m) => m.featured && m.category === "Pastry",
);

export const TAG_LABEL: Record<MenuTag, string> = {
  signature: "Signature",
  chef: "Rekomendasi Chef",
  spicy: "Pedas",
  new: "Baru",
};
